spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test  # 메모리 모드로 H2 사용
    username: sa  # 기본 사용자 이름
    password:
    platform: h2
  h2:
    console:
      enabled: true  # H2 콘솔 활성화
      path: /h2-console  # H2 콘솔 접속 경로 설정
  jpa:
    hibernate:
      ddl-auto: update  # DB 스키마 자동 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
# 서버 포트 설정
server:
  port: 8080